/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ice_cream;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;

/**
 *
 * @author Agung Kharisma
 */
public class ice_cream extends javax.swing.JFrame {

    ArrayList<String> mixerList = new ArrayList<>();
    double totalHarga=0;
    String TArea="";
    public ice_cream() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nama_icecream = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cocolate = new javax.swing.JCheckBox();
        vanila = new javax.swing.JCheckBox();
        strawbery = new javax.swing.JCheckBox();
        peanut = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        buttonGlass1 = new usu.widget.ButtonGlass();
        harga = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        total = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rincian = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        toko = new javax.swing.JComboBox();
        jalan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(374, 0, 0, 0);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pilih Ice Cream :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 90, 111, 17);

        nama_icecream.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gellato", "Turkish", "Clumpies" }));
        nama_icecream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_icecreamActionPerformed(evt);
            }
        });
        getContentPane().add(nama_icecream);
        nama_icecream.setBounds(130, 90, 100, 28);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cocolate           :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 128, 109, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Vanila                :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 167, 110, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Strowbery        :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 206, 110, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Peanut              :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 245, 110, 17);

        cocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocolateActionPerformed(evt);
            }
        });
        getContentPane().add(cocolate);
        cocolate.setBounds(125, 128, 21, 21);

        vanila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vanilaActionPerformed(evt);
            }
        });
        getContentPane().add(vanila);
        vanila.setBounds(126, 167, 21, 21);

        strawbery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawberyActionPerformed(evt);
            }
        });
        getContentPane().add(strawbery);
        strawbery.setBounds(126, 206, 21, 21);

        peanut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peanutActionPerformed(evt);
            }
        });
        getContentPane().add(peanut);
        peanut.setBounds(126, 245, 21, 21);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(252, 90, 212, 159);

        buttonGlass1.setText("Cost");
        buttonGlass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGlass1ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonGlass1);
        buttonGlass1.setBounds(10, 290, 95, 30);
        getContentPane().add(harga);
        harga.setBounds(130, 290, 100, 30);

        jButton2.setText("Total Biaya");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 333, 85, 23);
        getContentPane().add(total);
        total.setBounds(130, 330, 99, 30);

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel7.setText("SHEA ICE CREAM");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(154, 11, 163, 30);

        rincian.setColumns(20);
        rincian.setRows(5);
        jScrollPane1.setViewportView(rincian);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 250, 212, 110);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Pilih Toko Ice    :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 59, 113, 17);

        toko.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Food Truck", "IceCream Store" }));
        toko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokoActionPerformed(evt);
            }
        });
        getContentPane().add(toko);
        toko.setBounds(131, 59, 100, 28);

        jalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jalanActionPerformed(evt);
            }
        });
        getContentPane().add(jalan);
        jalan.setBounds(252, 59, 212, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ice_cream/co.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 490, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocolateActionPerformed

        if (cocolate.isSelected() == true) {
            mixerList.add("chocolate");
        }
    }//GEN-LAST:event_cocolateActionPerformed

    private void vanilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vanilaActionPerformed
        if (vanila.isSelected() == true) {
            mixerList.add("vanilla");
        }
    }//GEN-LAST:event_vanilaActionPerformed

    private void strawberyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawberyActionPerformed
        if (strawbery.isSelected() == true) {
            mixerList.add("strawberry");
        }
    }//GEN-LAST:event_strawberyActionPerformed

    private void peanutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peanutActionPerformed
        if (peanut.isSelected() == true) {
            mixerList.add("peanut");
        }
    }//GEN-LAST:event_peanutActionPerformed

    private void nama_icecreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_icecreamActionPerformed
   Object select1 = nama_icecream.getSelectedItem();
        if (select1 == "Gellato") {
        
            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ice_cream/Capture.JPG"))); // NOI18N
       
        }
        else if(select1=="Turkish") {
        
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ice_cream/ice.JPG"))); // NOI18N
       
        }
           
    }//GEN-LAST:event_nama_icecreamActionPerformed

    private void tokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokoActionPerformed
     Object select1 = toko.getSelectedItem();
        if (select1 == "Food Truck") {
            jalan.setVisible(true);
            String Jalan2=jalan.getText();
            rincian.setText(Jalan2);
        }
        else {
            jalan.setVisible(false);
        }
    }//GEN-LAST:event_tokoActionPerformed

    private void buttonGlass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGlass1ActionPerformed
        
        //FoodTruckIceCream truckA = new FoodTruckIceCream();

       //ArrayList<String> mixerListTruck = new ArrayList<>();
        //mixerListTruck.add("chocolate");
        //mixerListTruck.add("strawberry");
        //truckA.setLocation("jl. Veteran no.1 Malang");
        //truckA.orderIceCream("gellato", mixerListTruck);
        Object select1 = nama_icecream.getSelectedItem();

        if (select1 == "Clumpies") {
            AbstractIceCreamStore storeA = new IceCreamStore();
            double v = storeA.orderIceCream("clumpies", mixerList).cost();
            harga.setText(String.valueOf(v));
            totalHarga=totalHarga+v;
            total.setText(String.valueOf(totalHarga));
            TArea+="Anda membeli Clumpish\n";
            rincian.setText(TArea);

        } else if (select1 == "Turkish") {
            AbstractIceCreamStore storeA = new IceCreamStore();
            double v = storeA.orderIceCream("turkish", mixerList).cost();
            harga.setText(String.valueOf(v));
            totalHarga=totalHarga+v;
            total.setText(String.valueOf(totalHarga));
            TArea+="Anda membeli Turkish\n";
            rincian.setText(TArea);


        } else {
            AbstractIceCreamStore storeA = new IceCreamStore();
            double v = storeA.orderIceCream("gellato", mixerList).cost();
            harga.setText(String.valueOf(v));
            totalHarga=totalHarga+v;
            total.setText(String.valueOf(totalHarga));
        }


    }//GEN-LAST:event_buttonGlass1ActionPerformed

    private void jalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jalanActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jalanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ice_cream.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ice_cream.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ice_cream.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ice_cream.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               ice_cream kkk =new ice_cream();
                kkk.setVisible(true);
                kkk.setSize(500, 420);
                Dimension posisi = Toolkit.getDefaultToolkit().getScreenSize();

                int x = (posisi.width - kkk.getWidth()) / 2;

                int y = (posisi.height - kkk.getHeight()) / 2;

                kkk.setLocation(x, y);

                          
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.ButtonGlass buttonGlass1;
    private javax.swing.JCheckBox cocolate;
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jalan;
    private javax.swing.JComboBox nama_icecream;
    private javax.swing.JCheckBox peanut;
    private javax.swing.JTextArea rincian;
    private javax.swing.JCheckBox strawbery;
    private javax.swing.JComboBox toko;
    private javax.swing.JTextField total;
    private javax.swing.JCheckBox vanila;
    // End of variables declaration//GEN-END:variables
}
